
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 26 23:38:37 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 6;
  public static final int SEMICOLON = 21;
  public static final int PLUS = 13;
  public static final int LEFT_BRACE = 27;
  public static final int CHARACTER = 11;
  public static final int DIVISION = 16;
  public static final int DECREMENT = 20;
  public static final int RETURN = 7;
  public static final int IDENTIFIER = 9;
  public static final int HASH = 29;
  public static final int PROGRAM = 2;
  public static final int BOOLEAN = 12;
  public static final int LEFT_PARENTHESIS = 23;
  public static final int EQUALS = 18;
  public static final int COMMA = 22;
  public static final int RIGHT_PARENTHESIS = 24;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int MULTIPLICATION = 15;
  public static final int INCREMENT = 19;
  public static final int MINUS = 14;
  public static final int LEFT_BRACKET = 25;
  public static final int CONST = 3;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int NEW = 4;
  public static final int RIGHT_BRACE = 28;
  public static final int VOID = 8;
  public static final int MODULUS = 17;
  public static final int RIGHT_BRACKET = 26;
}

